export interface Talk {
  number: number;
  title: string;
}

export const allTalks: Talk[] = [
  { number: 1, title: "Você conhece bem a Deus?" },
  { number: 2, title: "Você vai sobreviver aos últimos dias?" },
  { number: 3, title: "Você está avançando com a organização unida de Jeová?" },
  { number: 4, title: "Que provas temos de que Deus existe?" },
  { number: 5, title: "Você pode ter uma família feliz!" },
  { number: 6, title: "O Dilúvio dos dias de Noé e você" },
  { number: 7, title: "Imite a misericórdia de Jeová" },
  { number: 8, title: "Viva para fazer a vontade de Deus" },
  { number: 9, title: "Escute e faça o que a Bíblia diz" },
  { number: 10, title: "Seja honesto em tudo" },
  { number: 11, title: "Imite a Jesus e não faça parte do mundo" },
  { number: 12, title: "Deus quer que você respeite quem tem autoridade" },
  { number: 13, title: "Qual o ponto de vista de Deus sobre o sexo e o casamento?" },
  { number: 14, title: "Um povo puro e limpo honra a Jeová" },
  { number: 15, title: "‘Faça o bem a todos’" },
  { number: 16, title: "Seja cada vez mais amigo de Jeová" },
  { number: 17, title: "Glorifique a Deus com tudo o que você tem" },
  { number: 18, title: "Faça de Jeová a sua fortaleza" },
  { number: 19, title: "Como você pode saber seu futuro?" },
  { number: 20, title: "Chegou o tempo de Deus governar o mundo?" },
  { number: 21, title: "Dê valor ao seu lugar no Reino de Deus" },
  { number: 22, title: "Você está usando bem o que Jeová lhe dá?" },
  { number: 23, title: "A vida tem objetivo" },
  { number: 24, title: "Você encontrou “uma pérola de grande valor”?" },
  { number: 25, title: "Lute contra o espírito do mundo" },
  { number: 26, title: "Você é importante para Deus?" },
  { number: 27, title: "Como construir um casamento feliz" },
  { number: 28, title: "Mostre respeito e amor no seu casamento" },
  { number: 29, title: "As responsabilidades e recompensas de ter filhos" },
  { number: 30, title: "Como melhorar a comunicação na família" },
  { number: 31, title: "Você tem consciência da sua necessidade espiritual?" },
  { number: 32, title: "Como lidar com as ansiedades da vida" },
  { number: 33, title: "Quando vai existir verdadeira justiça?" },
  { number: 34, title: "Você vai ser marcado para sobreviver?" },
  { number: 35, title: "É possível viver para sempre? O que você precisa fazer?" },
  { number: 36, title: "Será que a vida é só isso?" },
  { number: 37, title: "Obedecer a Deus é mesmo a melhor coisa a fazer?" },
  { number: 38, title: "Como você pode sobreviver ao fim do mundo?" },
  { number: 39, title: "Jesus Cristo vence o mundo — Como e quando?" },
  { number: 40, title: "O que vai acontecer em breve?" },
  { number: 41, title: "Fiquem parados e vejam como Jeová os salvará" },
  { number: 42, title: "O amor pode vencer o ódio?" },
  { number: 43, title: "Tudo o que Deus nos pede é para o nosso bem" },
  { number: 44, title: "Como os ensinos de Jesus podem ajudar você?" },
  { number: 45, title: "Continue andando no caminho que leva à vida" },
  { number: 46, title: "Fortaleça sua confiança em Jeová" },
  { number: 47, title: "(Não use.)" },
  { number: 48, title: "Seja leal a Deus mesmo quando for testado" },
  { number: 49, title: "Será que um dia a Terra vai ser limpa?" },
  { number: 50, title: "Como sempre tomar as melhores decisões" },
  { number: 51, title: "Será que a verdade da Bíblia está mudando a sua vida?" },
  { number: 52, title: "Quem é o seu Deus?" },
  { number: 53, title: "Você pensa como Deus?" },
  { number: 54, title: "Fortaleça sua fé em Deus e em suas promessas" },
  { number: 55, title: "Você está fazendo um bom nome perante Deus?" },
  { number: 56, title: "Existe um líder em quem você pode confiar?" },
  { number: 57, title: "Como suportar perseguição" },
  { number: 58, title: "Quem são os verdadeiros seguidores de Cristo?" },
  { number: 59, title: "(Não use.)" },
  { number: 60, title: "Você tem um objetivo na vida?" },
  { number: 61, title: "Nas promessas de quem você confia?" },
  { number: 62, title: "Onde encontrar uma esperança real para o futuro?" },
  { number: 63, title: "Tem você espírito evangelizador?" },
  { number: 64, title: "Você ama os prazeres ou a Deus?" },
  { number: 65, title: "Como podemos ser pacíficos num mundo cheio de ódio" },
  { number: 66, title: "Você também vai participar na colheita?" },
  { number: 67, title: "Medite na Bíblia e nas criações de Jeová" },
  { number: 68, title: "‘Continuem a perdoar uns aos outros liberalmente’" },
  { number: 69, title: "Por que mostrar amor abnegado?" },
  { number: 70, title: "Por que Deus merece sua confiança?" },
  { number: 71, title: "‘Mantenha-se desperto’ — Por que e como?" },
  { number: 72, title: "O amor identifica os cristãos verdadeiros" },
  { number: 73, title: "Você tem “um coração sábio”?" },
  { number: 74, title: "Os olhos de Jeová estão em todo lugar" },
  { number: 75, title: "Mostre que você apoia o direito de Jeová governar" },
  { number: 76, title: "Princípios bíblicos — Podem nos ajudar a lidar com os problemas atuais?" },
  { number: 77, title: "“Sempre mostrem hospitalidade”" },
  { number: 78, title: "Sirva a Jeová com um coração alegre" },
  { number: 79, title: "Você vai escolher ser amigo de Deus?" },
  { number: 80, title: "Você baseia sua esperança na ciência ou na Bíblia?" },
  { number: 81, title: "Quem está qualificado para fazer discípulos?" },
  { number: 82, title: "(Não use.)" },
  { number: 83, title: "Será que os cristãos precisam obedecer aos Dez Mandamentos?" },
  { number: 84, title: "Escapará do destino deste mundo?" },
  { number: 85, title: "Boas notícias num mundo violento" },
  { number: 86, title: "Como orar a Deus e ser ouvido por ele?" },
  { number: 87, title: "Qual é a sua relação com Deus?" },
  { number: 88, title: "Por que viver de acordo com os padrões da Bíblia?" },
  { number: 89, title: "Quem tem sede da verdade, venha!" },
  { number: 90, title: "Faça o máximo para alcançar a verdadeira vida!" },
  { number: 91, title: "A presença do Messias e seu domínio" },
  { number: 92, title: "O papel da religião nos assuntos do mundo" },
  { number: 93, title: "Desastres naturais — Quando vão acabar?" },
  { number: 94, title: "A religião verdadeira atende às necessidades da sociedade humana" },
  { number: 95, title: "Não seja enganado pelo ocultismo!" },
  { number: 96, title: "O que vai acontecer com as religiões?" },
  { number: 97, title: "Permaneçamos inculpes em meio a uma geração pervertida" },
  { number: 98, title: "“A cena deste mundo está mudando”" },
  { number: 99, title: "Por que podemos confiar no que a Bíblia diz?" },
  { number: 100, title: "Como fazer amizades fortes e verdadeiras" },
  { number: 101, title: "Jeová é o “Grandioso Criador”" },
  { number: 102, title: "Preste atenção à “palavra profética”" },
  { number: 103, title: "Como você pode ter a verdadeira alegria?" },
  { number: 104, title: "Pais, vocês estão construindo com materiais à prova de fogo?" },
  { number: 105, title: "Somos consolados em todas as nossas tribulações" },
  { number: 106, title: "Arruinar a Terra provocará retribuição divina" },
  { number: 107, title: "Você está treinando bem a sua consciência?" },
  { number: 108, title: "Você pode encarar o futuro com confiança!" },
  { number: 109, title: "O Reino de Deus está próximo" },
  { number: 110, title: "Deus vem primeiro na vida familiar bem sucedida" },
  { number: 111, title: "É possível que a humanidade seja completamente curada?" },
  { number: 112, title: "(Não use.)" },
  { number: 113, title: "Jovens — Como vocês podem ter uma vida feliz?" },
  { number: 114, title: "Apreço pelas maravilhas da criação de Deus" },
  { number: 115, title: "Não caia nas armadilhas de Satanás" },
  { number: 116, title: "Escolha sabiamente com quem irá associar se!" },
  { number: 117, title: "Como vencer o mal com o bem" },
  { number: 118, title: "Olhemos os jovens do ponto de vista de Jeová" },
  { number: 119, title: "Por que é benéfico que os cristãos vivam separados do mundo" },
  { number: 120, title: "Por que se submeter à regência de Deus agora" },
  { number: 121, title: "Uma família mundial que será salva da destruição" },
  { number: 122, title: "(Não use.)" },
  { number: 123, title: "(Não use.)" },
  { number: 124, title: "Razões para crer que a Bíblia é de autoria divina" },
  { number: 125, title: "Por que a humanidade precisa de resgate" },
  { number: 126, title: "Quem se salvará?" },
  { number: 127, title: "O que acontece quando morremos?" },
  { number: 128, title: "É o inferno um lugar de tormento ardente?" },
  { number: 129, title: "O que a Bíblia diz sobre a Trindade?" },
  { number: 130, title: "A Terra permanecerá para sempre" },
  { number: 131, title: "(Não use.)" },
  { number: 132, title: "Ressurreição — A vitória sobre a morte!" },
  { number: 133, title: "Tem importância o que cremos sobre a nossa origem?" },
  { number: 134, title: "Será que os cristãos precisam guardar o sábado?" },
  { number: 135, title: "A santidade da vida e do sangue" },
  { number: 136, title: "Será que Deus aprova o uso de imagens na adoração?" },
  { number: 137, title: "Ocorreram realmente os milagres da Bíblia?" },
  { number: 138, title: "Viva com bom juízo num mundo depravado" },
  { number: 139, title: "Sabedoria divina num mundo científico" },
  { number: 140, title: "Quem é realmente Jesus Cristo?" },
  { number: 141, title: "Quando terão fim os gemidos da criação humana?" },
  { number: 142, title: "Por que refugiar se em Jeová" },
  { number: 143, title: "Confie no Deus de todo consolo" },
  { number: 144, title: "Uma congregação leal sob a liderança de Cristo" },
  { number: 145, title: "Quem é semelhante a Jeová, nosso Deus?" },
  { number: 146, title: "Use a educação para louvar a Jeová" },
  { number: 147, title: "Confie que Jeová tem o poder para nos salvar" },
  { number: 148, title: "Você tem o mesmo conceito de Deus sobre a vida?" },
  { number: 149, title: "O que significa “andar com Deus”?" },
  { number: 150, title: "Este mundo está condenado à destruição?" },
  { number: 151, title: "Jeová é “uma altura protetora” para seu povo" },
  { number: 152, title: "Armagedom — Por que e quando?" },
  { number: 153, title: "Tenha bem em mente o “atemorizante dia”!" },
  { number: 154, title: "O governo humano é pesado na balança" },
  { number: 155, title: "Chegou a hora do julgamento de Babilônia?" },
  { number: 156, title: "O Dia do Juízo — Tempo de temor ou de esperança?" },
  { number: 157, title: "Como os verdadeiros cristãos adornam o ensino divino" },
  { number: 158, title: "Seja corajoso e confie em Jeová" },
  { number: 159, title: "Como encontrar segurança num mundo perigoso" },
  { number: 160, title: "Mantenha a identidade cristã!" },
  { number: 161, title: "Por que Jesus sofreu e morreu?" },
  { number: 162, title: "Seja liberto deste mundo em escuridão" },
  { number: 163, title: "Por que temer o Deus verdadeiro?" },
  { number: 164, title: "Será que Deus ainda está no controle?" },
  { number: 165, title: "Os valores de quem você preza?" },
  { number: 166, title: "Verdadeira fé — O que é e como mostrar" },
  { number: 167, title: "Ajamos sabiamente num mundo insensato" },
  { number: 168, title: "Você pode sentir se seguro neste mundo atribulado!" },
  { number: 169, title: "Por que ser orientado pela Bíblia?" },
  { number: 170, title: "Quem está qualificado para governar a humanidade?" },
  { number: 171, title: "Poderá viver em paz agora — E para sempre!" },
  { number: 172, title: "Que reputação você tem perante Deus?" },
  { number: 173, title: "Existe uma religião verdadeira do ponto de vista de Deus?" },
  { number: 174, title: "Quem se qualificará para entrar no novo mundo de Deus?" },
  { number: 175, title: "O que prova que a Bíblia é autêntica?" },
  { number: 176, title: "Quando haverá verdadeira paz e segurança?" },
  { number: 177, title: "Onde encontrar ajuda em tempos de aflição?" },
  { number: 178, title: "Ande no caminho da integridade" },
  { number: 179, title: "Rejeite as fantasias do mundo, empenhe-se pelas realidades do Reino" },
  { number: 180, title: "A ressurreição — Por que essa esperança deve ser real para você" },
  { number: 181, title: "Já é mais tarde do que você imagina?" },
  { number: 182, title: "O que o Reino de Deus está fazendo por nós agora?" },
  { number: 183, title: "Desvie seus olhos do que é fútil" },
  { number: 184, title: "A morte é o fim de tudo?" },
  { number: 185, title: "Será que a verdade influencia sua vida?" },
  { number: 186, title: "Sirva em união com o povo feliz de Deus" },
  { number: 187, title: "Por que um Deus amoroso permite a maldade?" },
  { number: 188, title: "Você confia em Jeová?" },
  { number: 189, title: "Ande com Deus e receba bênçãos para sempre" },
  { number: 190, title: "Como se cumprirá a promessa de perfeita felicidade familiar" },
  { number: 191, title: "Como o amor e a fé vencem o mundo" },
  { number: 192, title: "Você está no caminho para a vida eterna?" },
  { number: 193, title: "Os problemas de hoje logo serão coisa do passado" },
  { number: 194, title: "Como a sabedoria de Deus nos ajuda" },
];
