export const API_ROUTES = {
    TERRITORY: "/territory",
    CONGREGATION: "/congregation",
    PUBLISHER: "/publisher", 
    PUBLISHERS: "/publishers",
    CATEGORY: "/category",
    TERRITORYHISTORY: "/territoryHistory",
    ROLE: "/role",
    PERMISSION: "/permission", 
    NOTICE: "/notice",
    REPORT: "/report",
    GROUP: "/group", 
    ASSISTANCE: "/assistance", 
    CLEANING_GROUPS: "/cleaning/groups",
    CLEANING_SCHEDULES_CONFIG: "/cleaning/schedule-config",
    CLEANING_SCHEDULES: "/cleaning/schedule",
    CLEANING_EXCEPTIONS: "/cleaning-exception",
    FAMILIES: "/families", 
    PUBLIC_WITNESS_ARRANGEMENTS: "/public-witness/arrangements",
    FIELD_SERVICE_TEMPLATES: "/field-service/templates",
    FIELD_SERVICE_EXCEPTIONS: "/field-service/exceptions",
    FIELD_SERVICE_SCHEDULES: "/field-service/schedules",
}